### ISSUE TITLE
Callback function for scan should be on global scope in Rails App

### ISSUE THREAD

**Issue by rvgarimrj** [bridgeit/bridgeit.js#55]
I tried to make it work on a Ruby On Rails app but when I click the scan button, after scanning it says that the callback function must be on global scope.

**Comment by philipbreau** [comment]
Can you show the relevant code? Have you tried attaching the callback to window scope manually like so?

`
window.onAfterCaptureScan = function(event)  {
        console.log('onAfterCaptureScan: ' + JSON.stringify(event));
        var HTTP = "http";
        var text = event.value;
        if (HTTP == text.substring(0, HTTP.length))  {
            text = "<span class='ellipsis'><a href='" + text + "'>" + text + "</a></span>";
        }
        var scans = document.getElementById("scans");
        var row1 = document.createElement('div');
        row1.setAttribute('class','row timestamp');
        row1.innerHTML = "<span class='ellipsis'>Scanned on " + new Date() + "</span>";
        var row2 = document.createElement('div');
        row2.setAttribute('class','row');
        row2.innerHTML = text;
        scans.insertBefore(row1, scans.firstChild);
        scans.insertBefore(row2, scans.firstChild);
}
`

**Comment by rvgarimrj** [comment]
Sure.

I created a gist to make things easier.
(https://gist.github.com/rvgarimrj/2e6187a7c4088c71bdd3)

On *application.html.erb* you will find the right tag to include the api.

On *application.js *you will find the method onAfterCaptureScan.

On *detail_fields.html.erb* you will see the scanBtn id where I call the
bridgeit.scan

Also, the problem is that *I need to call another function after getting
the value from onAfterCaptureScan*.I only put an alert on that function
that I need to call (novo_cod_barras) to see if it is being called. And
then I get the error saying that *onAfterCaptureScan must be in global
scope*.

Appreciate your help
Best Regards
Gabriel


2016-03-16 8:32 GMT-03:00 Philip Breau <notifications@github.com>:

**Comment by philipbreau** [comment]
The problem might be that novo_cod_barras function is not in the right scope when onAfterCaptureScan tries to call it. If there's an uncaught error in the callback function, BridgeIt will still give you that 'not in global scope' error.

Try this.

https://gist.github.com/philipbreau/c07e59f8eefd4c13b378

**Comment by rvgarimrj** [comment]
Tks Philip, now it is working. One last thing. My window.novo_cod_barras
function was written ,initially, as a jquery function. I know it some kind
of out of this issue scope , but can it be used inside this
window.novo_cod_barras as jquery or i must write it only in javascript
language?

tks again for the patience
regards
Gabriel


2016-03-17 14:40 GMT-03:00 Philip Breau <notifications@github.com>:

**Comment by philipbreau** [comment]
No, you can use jquery or anything you want. As long as it's loaded before your callback fires, then you should be fine. When you reference $, you're referencing window.$, so it's fine.

**Comment by rvgarimrj** [comment]
Tks Philip
Em 18/03/2016 09:33, "Philip Breau" <notifications@github.com> escreveu:

**Comment by rvgarimrj** [comment]
Philip, one last question. I need to pass the target event to a function.
In my OnAfterScanCapture i'm doing like so:

window.onAfterCaptureScan = function(event)
{
  try{
     // alert('entering onAfterCaptureScan()');
      var target = event.target;
      var parent = target.parentElement;//parent of "target"
      var parent1 = $(parent).parents('.nested-fields');
      var valor = event.value;
so I get Cannot read property 'parentElement' of undefined.

Should I open another issue?can you help me on that ?

regards



2016-03-18 10:23 GMT-03:00 Gabriel Madeira <gabriel.madeira1@gmail.com>:

**Comment by philipbreau** [comment]
Hi,
    There is no target on the returned event, as the callback comes from the native bridge and not a user event. If you want to store the target, you should probably capture that before firing the bridgeit.scan() function.

**Comment by rvgarimrj** [comment]
That was i thought too. Do you have any idea of how can i do to store the
target before firing the callback without loosing the actual bridgeit
functionality?
Thank you in advanced.
Best regards
Gabriel
Em 21/03/2016 19:59, "Philip Breau" <notifications@github.com> escreveu:
